name: multivendor_app
description: ALTIYOL pazaryeri

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.1.41+42

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dots_indicator: any
  #firebase-related
  firebase_auth: any
  cloud_firestore: any
  firebase_core: any
  firebase_messaging: any
  firebase_crashlytics: any

  provider: any
  cupertino_icons: any
  geolocator: any
  flutter_spinkit: any
  shared_preferences: any
  carousel_slider: any
  paginate_firestore: any
  persistent_bottom_nav_bar: any
  url_launcher: any
  expandable_text: any
  flutter_easyloading: any
  toggle_bar: any
  dotted_border: any
  chips_choice: any
  sizer: any
  auto_size_text: any


  #not supported for ios

  #not supported for web
  social_share: any
  map_launcher: any
  geocoder: any
  google_maps_flutter: any


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
    - images/

  fonts:
    - family: Lato
      fonts:
        - asset: fonts/Lato-Bold.ttf
          weight: 700
        - asset: fonts/Lato-Regular.ttf

    - family: Anton
      fonts:
        - asset: fonts/Anton-Regular.ttf

    - family: CaviarDreams
      fonts:
        - asset: fonts/CaviarDreams_Bold.ttf
          weight: 700
        - asset: fonts/CaviarDreams.ttf
